language: java

services:
  - docker

jdk:
  - openjdk8
  - openjdk11
  - openjdk16

cache:
  directories:
    - .autoconf

env:
  matrix:
    - TEST_SET="-Ptravis_e2e_skip"
    - TEST_SET="-Ptravis_e2e"
    - TEST_SET="glassfish-copyright:check"

before_install:
  - jdk_switcher use $TRAVIS_JDK_VERSION
  - export JAVA_HOME=$(jdk_switcher home $TRAVIS_JDK_VERSION)
  - echo "JAVA_HOME=$JAVA_HOME"
  - java -version
  - mvn -version


install: true

script:
  - bash etc/travis/travis.sh $TEST_SET

git:
  depth: false